### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by wellencamass** [sw33tLie/sns#2]
Running sns on some services gives kernell panic
<img width="910" alt="изображение" src="https://user-images.githubusercontent.com/77920409/166147577-732ef3d7-6c5b-4560-9ccd-521773ffe39e.png">

Its shodan - based IP with IIS 7.0 to check how tool handles different services

**Comment by wellencamass** [comment]
Hello, any updates? :)

**Comment by fsacer** [comment]
Got the same issue with go1.17.8. Seems to happen if site is not https.

**Comment by sw33tLie** [comment]
Apologies for the delay, i'll release a fix shortly.
The good thing is that as far as I can tell it should only happen with not-vulnerable targets.
